### PR TITLE
Optimize crawler

### LINKED ISSUE #23: HTTP errors while using `depth` argument
Actually, HTTP errors are supported, but when they're "depthed", they're always handled as exceptions, breaking the script, so it seems these should be caught and rendered as classic errored-crawls...

Here is an example of use:

``` bash
$ centipede run http://example.com/
200 http://example.com/page
404 http://example.com/non_existing
```

If I'm using the `depth` argument, once the crawler reaches a page while the "current depth" is different than the root one, errors are no more handled.

In the above example, suppose there is a link on the `/page` page pointing on `/non_existing`, the result will be similar to this one:

``` bash
$ centipede run http://example.com/ 1
200 http://example.com/page

  [GuzzleHttp\Exception\ClientException]
  Client error response [url] http://example.com/non_existing [status code] 404 [reason phrase] Not Found

```

This breaks the script and the crawler can no more be able to navigate, obviously.

### PR DESCRIPTION
**Pull request by Pierstoval**
Fixes #23

### CODE REVIEW

**Comment by umpirsky** [comment]
Very nice, thanks for your contribution @Pierstoval, really appreciate it. :+1: 

This depends on https://github.com/umpirsky/centipede-crawler/pull/8, right, so I think we need to update composer dependency for the crawler `composer update umpirsky/centipede-crawler`.

If that does not work because of stability stable, just ping me after we merge PR and I will tag a new release.

**Comment by umpirsky** [comment]
Later I may extract request handling from this command and introduce formatters. :)

**Comment by Pierstoval** [comment]
There are still some bugs with ClientException, I'm gonna fix this, just wait a moment ;)

**Comment by umpirsky** [comment]
@Pierstoval In which cases is `ClientException` thrown?

**Comment by Pierstoval** [comment]
When the `$response->getStatusCode()` returns special errors. I tested on an url that returns a HTTP 406 error, and this function returned an exception.

**Comment by umpirsky** [comment]
@Pierstoval Cool, so you can remove exception handling from centipede now?

**Comment by Pierstoval** [comment]
Done ! Also fixed depth rendering in both repositories

**Comment by Pierstoval** [comment]
I'm not sure I'm going to continue working on this, sorry. Anyone can take the work back if necessary.

**Pull request closed without merging**
